"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashScreen from "@/components/SplashScreen";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const pathname = usePathname()
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(isHome);
  useEffect(() => {
    if (isLoading) return
  }, [isLoading]);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <body className="bg-full bg-red-900 bg-fixed bg-no-repeat">
          {/* we are saying that if ishome and isloading is true show splashscreen but if it not true just the page content  */}
          {isLoading && isHome ? (
            <SplashScreen finishloading={()=> setIsLoading(false)} />
          ) : (
              
          <>
            {/* {/* <Navbar /> */}
            {children}
            {/* <Footer/> */} 
          </>
          )}
        </body>
      </head>
     
    </html>
  );
}
